import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import Header from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
          <Providers>
            <Header/>
            {children}
          </Providers>
      </body>
    </html>
  );
}



// import { NextRequest, NextResponse } from "next/server"

// const protectedRoutes = ["/dashboard", "/profile", "/settings"]
// const authRoutes = ["/login", "/register"]

// export function middleware(req: NextRequest) {
//     const { pathname } = req.nextUrl
//     const refreshToken = req.cookies.get("refreshToken")?.value

//     const isProtected = protectedRoutes.some((r) => pathname.startsWith(r))
//     const isAuthRoute = authRoutes.some((r) => pathname.startsWith(r))

//     // protected route-ზე cookie გარეშე → login
//     if (isProtected && !refreshToken) {
//         return NextResponse.redirect(new URL("/login", req.url))
//     }

//     // login/register-ზე cookie-ით → dashboard
//     if (isAuthRoute && refreshToken) {
//         return NextResponse.redirect(new URL("/dashboard", req.url))
//     }

//     return NextResponse.next()
// }

// export const config = {
//     matcher: ["/((?!_next/static|_next/image|favicon.ico|api).*)"]
// }